<?php
  require_once("OralHistoryDataConn.php");
  require_once("LookupFunctions.php");
  require_once("settings.php");
  $ModBy = $_SESSION['s_user_id'];
  $DateMod = date('Y-m-d');

  $o = "";

  // The form was not submitted; get the primary key value...
  $UserId=$_GET['U'];

  if ($UserId > 0) :
      // This is an existing record, so read it...
      $query="SELECT * FROM users WHERE UserId = '$UserId'";
      $result = mysqli_query($conn, $query);
      $fields = mysqli_fetch_assoc($result);
      $UserId = $fields["UserId"];
      $UserName = $fields["UserName"];
      $UserAddress = $fields["UserAddress"];
      $UserPhone = $fields["UserPhone"];
      $UserMobilePhone = $fields["UserMobilePhone"];
      $UserFax = $fields["UserFax"];
      $UserEmail = $fields["UserEmail"];
      $UserURL = $fields["UserURL"];
      $UserPwReminder = $fields["UserPwReminder"];
      $CountryID = $fields["CountryID"];
      $IsAdmin = $fields["IsAdmin"];
      $CanUpload = $fields["CanUpload"];
      $AnnotatesOwn = $fields["AnnotatesOwn"];
      $AnnotatesAll = $fields["AnnotatesAll"];
      $CanDownload = $fields["CanDownload"];
      $CanAdd = $fields["CanAdd"];
      $CanModify = $fields["CanModify"];
      $EnteredBy = $fields["EnteredBy"];
      $DateEntered = $fields["DateEntered"];
      $Title .= "Edit $UserName's Record...";
  else :
      // This is a new record, which has not yet been submitted...
      // These are the default values...
      $IsAdmin = 0;
      $CanUpload = 1;
      $AnnotatesOwn = 1;
      $AnnotatesAll = 0;
      $CanDownload = 0;
      $CanAdd = 0;
      $CanModify = 0;
      $Salt = "Oral History Project 2014";
      $DateEntered = $DateMod;

      $Title = "Enter a new User Record.  Fill in the form and press 'Submit'...\n";
  endif;

  $o .= "<div class=centered>\n";
  $o .= "  <form name=formReg id=formReg method=post>\n";
  $o .= "    <input type='hidden' name='UserId' value=\'$UserId\'>\n";
  $o .= "    <input type='hidden' name='Salt' value='$Salt'>\n";
  $o .= "    <input type='hidden' name='EnteredBy' value='$EnteredBy'>\n";
  $o .= "    <input type='hidden' name='DateEntered' value='$DateEntered'>\n";
  $o .= "    <input type='hidden' name='Action' value=''>\n";
  $o .= "    <table rules=rows class=rv style='width: 100%; font-size: 9pt;'>\n";
  $o .= "      <thead><tr class=colname>\n";
  $o .= "        <td colspan=6>$Title</td>\n";
  $o .= "      </tr></thead>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td class=caption>User Name<span style='color:red'>*</span> :</td>\n";
  $o .= "          <td colspan=5>\n";
  $o .= "            <input type='text' style='width:420px' name='UserName' id='UserName' value='$UserName' >\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row0>\n";
  $o .= "          <td class=caption>Address<span style='color:red'>*</span> :</td>\n";
  $o .= "          <td colspan=5>\n";
  $o .= "            <textarea name='UserAddress' wrap='SOFT' rows=3 style='width: 100%;' >$UserAddress</textarea>\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td class=caption>Phone<span style='color:red'>*</span> :</td>\n";
  $o .= "          <td>\n";
  $o .= "            <input type='text' style='width:90px' name='UserPhone' id='UserPhone' value='$UserPhone' onChange='isPhoneNumber(this.id); return false'>\n";
  $o .= "          </td>\n";
  $o .= "          <td style='width:200px'>\n";
  $o .= "            <span class='mini'> North America Format: (555) 555-1234.<br>International Format: digits 0-9 only.</span>\n";
  $o .= "          </td>\n";
  $o .= "          <td class=caption>Mobile :</td>\n";
  $o .= "          <td>\n";
  $o .= "            <input type='text' style='width:90px' name='UserMobilePhone' id='UserMobilePhone' value='$UserMobilePhone' onChange='isPhoneNumber(this.id); return false'>\n";
  $o .= "          </td>\n";
  $o .= "          <td style='width:200px'>\n";
  $o .= "            <span class='mini'> North America Format: (555) 555-1234.<br>International Format: digits 0-9 only.</span>\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row0>\n";
  $o .= "          <td class=caption>Fax :</td>\n";
  $o .= "          <td>\n";
  $o .= "            <input type='text' style='width:90px' name='UserFax' id='UserFax' value='$UserFax' onChange='isPhoneNumber(this.id); return false'>\n";
  $o .= "          </td>\n";
  $o .= "          <td style='width:200px'>\n";
  $o .= "             <span class='mini'> North America Format: (555) 555-1234.<br>International Format: digits 0-9 only.</span>\n";
  $o .= "          </td>\n";
  $o .= "          <td class=caption>E-mail<span style='color:red'>*</span> :</td>\n";
  $o .= "          <td colspan=3>\n";
  $o .= "            <input type='text' name='UserEmail' id='UserEmail' value='$UserEmail'  onChange='checkEmail(this.id)' >\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td class=caption>URL :</td>\n";
  $o .= "          <td colspan=5>\n";
  $o .= "            <input type='text' style='width:700px' name='UserURL' id='UserURL' value='$UserURL' onChange='isURL(this.id)' >\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row0>\n";
  if ($UserId < 1 || is_null($UserId)) :
      // Allow password fields...
      $o .= "          <td class=caption>Password<span style='color:red'>*</span> :</td>\n";
      $o .= "          <td><input type='password' name='UserPw' value='' ></td>\n";
      $o .= "          <td class=caption>Pw Reminder<span style='color:red'>*</span> :</td>\n";
      $o .= "          <td colspan=3><input type='text' style='width:380px' name='UserPwReminder' id='UserPwReminder' value='$UserPwReminder'></td>\n";
  else :
      $o .= "          <td class=caption>Password :</td>\n";
      $o .= "          <td>Not Retreivable</td>\n";
      $o .= "          <td class=caption>Pw Reminder :</td>\n";
      $o .= "          <td colspan=3>$UserPwReminder</td>\n";
  endif;
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td class=caption>Country :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=              MakeLookup('CountryID','countries','CountryID','Name','List','Name',$CountryID);
  $o .= "          </td>\n";
  $o .= "          <td class=caption>Is Admin? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('IsAdmin','','IsAdmin','','YesNo','',$IsAdmin);
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row0>\n";
  $o .= "          <td class=caption>Can Upload? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('CanUpload','','CanUpload','','YesNo','',$CanUpload);
  $o .= "          </td>\n";
  $o .= "          <td class=caption>Tags Own? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('AnnotatesOwn','','AnnotatesOwn','','YesNo','',$AnnotatesOwn);
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td class=caption>Tags All? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('AnnotatesAll','','AnnotatesAll','','YesNo','',$AnnotatesAll);
  $o .= "          </td>\n";
  $o .= "          <td class=caption>Can Download? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('CanDownload','','CanDownload','','YesNo','',$CanDownload);
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row0>\n";
  $o .= "          <td class=caption>Can Add? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('CanAdd','','CanAdd','','YesNo','',$CanAdd);
  $o .= "          </td>\n";
  $o .= "          <td class=caption>Can Modify? :</td>\n";
  $o .= "          <td colspan=2>\n";
  $o .=             MakeLookup('CanModify','','CanModify','','YesNo','',$CanModify);
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tbody>\n";
  $o .= "        <tr class=row1>\n";
  $o .= "          <td colspan=6>\n";
  $o .= "            <div id=\"captchadiv\"></div>\n";
  $o .= "          </td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tbody>\n";
  $o .= "      <tfoot>\n";
  $o .= "        <tr class=colname>\n";
  $o .= "          <td colspan=6 style='vertical-align:middle'>\n";
  $o .= "            <input type='button' class='b2' id='Submit' value='Submit' onClick='verifyUser(\"formReg\",$UserId,0); return false;'>&nbsp;&nbsp;\n";
  $o .= "            <input type='button' class='b2' id='Reset' value='Reset' onclick='document.form.reset()'>&nbsp;&nbsp;\n";
  $o .= "            <input type='button' class='b2' onClick='clearDiv(\"recordView\");' value='Cancel'a> &nbsp; \n";
  $o .= "            <span class=bib>Fields with an asterisk(<span style='color:red'>*</span>) are required.</span></td>\n";
  $o .= "        </tr>\n";
  $o .= "      </tfoot>\n";
  $o .= "    </table>\n";
  $o .= "  </form>\n";
  if ($UserId>0):
      $o .= "  <br><a class=b1 href='#' onClick='showUserEntry(0);'>Add Another</a> &nbsp; \n";
  endif;
  $o .= "  <a class=b1 href='#' onClick='clearDiv(\"recordView\");'>Close</a> &nbsp; \n";
  $o .= "</div>\n";
  $o .= "<hr style='color:#1F3F5E;background-color:#1F3F5E;height:1px;border:none;'>\n";
  echo $o;
?>
<script src='javascripts/xmlhttp.js' language='javascript' type='text/javascript'></script>
<script src='javascripts/validate.js' language='javascript' type='text/javascript'></script>