<?php
  $f =  "      <div style='margin-top: 2em; clear:both; border-top: thin solid #1F3F5E'><table class=noborder style='margin-left:auto; margin-right:auto; width: 100%'>\n";
  $f .= "        <tr align=center>\n";
  $f .= "          <td width=37% style='text-align:left;'>\n";
  $f .= "            <p class=tiny style='text-indent:-6px;'>\n";
  $f .= "            <a href='http://gaialab.asu.edu/home' target='_top'><img src='images/fork.png' align=left border=0 style='margin-right: .5em'></a>&nbsp;\n";
  $f .= "            <span style='color:maroon;'>Office of Knowledge Enterprise Development</span><br>\n";
  $f .= "            Institute for Humanities Research/Nexus Lab<br>\n";
  $f .= "            Arizona State University, Box 876505<br>\n";
  $f .= "            Tempe, AZ  85287-6505<br>\n";
  $f .= "            Webmaster - <A HREF='mailto:shsavage@asu.edu'>shsavage@asu.edu</A>\n";
  $f .= "            </p>\n";
  $f .= "          </td>\n";
  $f .= "          <td width = 30% style='text-align:center;'>\n";
  $f .= "          </td>\n";
  $f .= "          <td width=33% style='text-align:center;'>\n";
  $f .= "          </td>\n";
  $f .= "        </tr>\n";
  $f .= "        <tr align=center>\n";
  $f .= "          <td width=37%>\n";
  $f .= "          </td>\n";
  $f .= "          <td width = 30% style='text-align: center'>\n";
  $f .= "          </td>\n";
  $f .= "          <td width=33%  style='text-align:center;'>\n";
  $f .= "          </td>\n";
  $f .= "        </tr>\n";
  $f .= "      </table>\n";
  echo $f;
  $f="";
?>
