<?php
  $o  = "<h2 class=center>Welcome to the ASU Social Scribe Project!</h2>\n";

  $o .= "<p>The ASU Social Scribe Project is a joint endeavor of the School of Historical, Philosophical & Religious Studies, the Office of Knowledge Enterprise Development, and the Institute for Humanities Research/Nexus Lab at Arizona State University. This experimental web application is designed to allow the public to hear and search oral histories on a variety of topics (compilations) through an interactive audio player like the image shown below. A few other web sites do something similar.  But our project lets registered users create compilations, upload oral history files (in .mp3 format) and create metadata and transcriptions for them, so that the public can access the files.</p>\n";

  $o .= "<div><div class='hbar'></div><h3 class=center>How it Works</h2><p>Through innovative annotation and transcription functions, registered users can add tags to their audio files, allowing them to be highlighted for easier navigation. The annotations appear as a listing beneath the audio file listening controls.  As a registered user adds annotations the list grows. Any user can click on the 'Listen' link beside an annotation; the audio file immediately jumps to that part of the oral history and plays it. Registered users can also create transcriptions of any audio file in the database. We do not resrict the creation of transcripts to audio files that \"belong\" to a registered user. Rather, we store each user's transcriptions for any audio file, which leverages the transcription process and gets multiple listeners involved. That can be especially helpful where accents or audio problems render transcribing difficult. And it also lets us create side-by-side comparisons of transcriptions.<br><div class=centered><img class=brdr src='images/PLAYER2.png'><img src='images/KEYWORD.png' align=right></div></p>\n";

  $o .= "<p>In addition to having annotations and transcriptions that let the user jump into oral histories at various points, the system we are developing supports keyword searches of audio file and annotation metadata. The metadata for each audio file and annotation contains descriptive text and a list of relevant keywords. When the user sees a listing of available audio files or their annotations, the list of keywords is included as a series of links. To find other audio files or annotations with any keyword, the user can simply click the keyword of their choice, or type their keyword search term in the \"Recordings Keyword Search\" box in the upper right corner of the page. Immediately, a result list is displayed, which the user can use to load and listen to other relevant audio files. In the sample illustration, the keyword \"irony\" was clicked, resulting in the list shown on the right.</p>\n";

  $o .= "<p>Most users will not find it necessary to register with us to use the system we're developing. That's only necessary if you want to contribute to our library of oral histories or transcribe an audio track. You can get started simply by pressing either the \"List Compilations\" button below or below the Log In form. If you are a registered user already, you can use the login form on the right to log in to the system, so you can upload audio files, and annotate the files you've uploaded.  Even if you're a registered user, you don't need to log in unless you want to upload or annotate audio files.  If you aren't a registered user, but you'd like to be, press the 'Register with the ASU OHP' button below, or the 'Register Here' button on the Log In form.</div></p>\n";

  $o .= "<div class=centered>\n";
  if ($DefaultCompilationId > 0) :
      $o .= "      <a href='#' class=b1 style='text-decoration: none' onClick='showRecordings($DefaultCompilationId)'>List Recordings</a> &nbsp; &nbsp;\n";
  else :
      $o .= "      <a href='#' class=b1 style='text-decoration: none' onClick='showCompilations(0,0)'>List Compilations</a> &nbsp; &nbsp;\n";
  endif;
  if ($AllowPublicRegistration == 1) { $o .= "  <a href='#' class=b2 style='text-decoration:none' onClick='showRegistration(0);'>Register with the ASU OHP</a>\n"; }
  $o .= "</div>\n";

  $o .= "<div class='hbar'></div><h3 class=center>A Data Structure for Oral History</h3><p><img src='images/DataStructure.png' align=right style='margin-left:.5em'>In the data structure we have developed for the project, \"Compilations\" refer to groups of audio resources related to the same theme or subject. These typically include interviews about the theme or subject of the Compilation, and we refer to these interviews as \"Recordings.\" Because recordings are often quite lengthy -- sometimes more than an hour -- we have divided them into \"Tracks,\" which are usually no more than three minutes in length. We do this to prevent issues in streaming very long .mp3 files. You'll see the available tracks when you click the \"List Recordings\" link next to a Compilation when you view the Compilations list.</p>\n";

  $o .= "<p>Annotations are text entries that highlight an audio track, for any number of reasons; they are time-stamped and linked to the audio track, so anyone can jump into the track at that point and listen to it. A \"Transcription\" is a specialized kind of annotation, where the timestamps are created by the system via \"Blocks\" -- five second-long chuncks of an audio track. We've done this to make it easier to create transcriptions. Any registered user can transcribe any recording tracks in our database, because we believe that \"the more ears, the better\" when it comes to transcriptions. Each registered user's transcriptions are kept separately, so multiple users can transcribe the same track, and we will be able to present the alternatives to all users.</p>\n"; 

  echo $o;
  $o = "";
?>